In [1]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


In [2]:
print 5

5


In [3]:
import numpy as np

In [4]:
arr1 = np.random.rand(100)

In [7]:
arr2 = arr1.reshape((25, 4))

In [8]:
print arr1


[  8.01583697e-01   3.93580786e-01   9.83279801e-02   7.63797256e-01
   2.24255755e-02   9.65606388e-01   2.55013921e-02   9.89088586e-01
   8.19061843e-01   3.00957364e-01   1.68628664e-01   7.56588017e-01
   1.86145015e-01   8.39635709e-01   8.03347987e-01   8.81358451e-01
   5.42748764e-01   7.92799490e-02   2.39845773e-01   3.56240871e-01
   9.43567412e-01   3.95289845e-01   4.29567266e-01   6.50783866e-01
   6.72711486e-01   1.51998909e-01   5.48897971e-01   4.54314452e-01
   5.66600378e-01   7.84016598e-01   9.94146205e-01   2.76583565e-02
   7.02269869e-01   3.61211019e-01   3.35761036e-06   9.93163335e-01
   9.07285369e-01   7.03632414e-01   5.87103715e-01   8.42372376e-01
   9.15469050e-01   5.23304415e-02   5.13534402e-01   8.65152720e-01
   1.76677140e-01   4.48338207e-01   5.56900794e-01   4.17238242e-02
   3.43416420e-01   2.80675069e-01   6.61921910e-01   5.18101807e-01
   5.16411467e-01   3.97227287e-01   7.81019707e-03   7.10696336e-01
   6.78403608e-01   3.63762208e-01

In [9]:
print arr2

[[  8.01583697e-01   3.93580786e-01   9.83279801e-02   7.63797256e-01]
 [  2.24255755e-02   9.65606388e-01   2.55013921e-02   9.89088586e-01]
 [  8.19061843e-01   3.00957364e-01   1.68628664e-01   7.56588017e-01]
 [  1.86145015e-01   8.39635709e-01   8.03347987e-01   8.81358451e-01]
 [  5.42748764e-01   7.92799490e-02   2.39845773e-01   3.56240871e-01]
 [  9.43567412e-01   3.95289845e-01   4.29567266e-01   6.50783866e-01]
 [  6.72711486e-01   1.51998909e-01   5.48897971e-01   4.54314452e-01]
 [  5.66600378e-01   7.84016598e-01   9.94146205e-01   2.76583565e-02]
 [  7.02269869e-01   3.61211019e-01   3.35761036e-06   9.93163335e-01]
 [  9.07285369e-01   7.03632414e-01   5.87103715e-01   8.42372376e-01]
 [  9.15469050e-01   5.23304415e-02   5.13534402e-01   8.65152720e-01]
 [  1.76677140e-01   4.48338207e-01   5.56900794e-01   4.17238242e-02]
 [  3.43416420e-01   2.80675069e-01   6.61921910e-01   5.18101807e-01]
 [  5.16411467e-01   3.97227287e-01   7.81019707e-03   7.10696336e-01]
 [  6.

In [10]:
arr3 = arr1.reshape((50, 2))

In [11]:
print arr3

[[  8.01583697e-01   3.93580786e-01]
 [  9.83279801e-02   7.63797256e-01]
 [  2.24255755e-02   9.65606388e-01]
 [  2.55013921e-02   9.89088586e-01]
 [  8.19061843e-01   3.00957364e-01]
 [  1.68628664e-01   7.56588017e-01]
 [  1.86145015e-01   8.39635709e-01]
 [  8.03347987e-01   8.81358451e-01]
 [  5.42748764e-01   7.92799490e-02]
 [  2.39845773e-01   3.56240871e-01]
 [  9.43567412e-01   3.95289845e-01]
 [  4.29567266e-01   6.50783866e-01]
 [  6.72711486e-01   1.51998909e-01]
 [  5.48897971e-01   4.54314452e-01]
 [  5.66600378e-01   7.84016598e-01]
 [  9.94146205e-01   2.76583565e-02]
 [  7.02269869e-01   3.61211019e-01]
 [  3.35761036e-06   9.93163335e-01]
 [  9.07285369e-01   7.03632414e-01]
 [  5.87103715e-01   8.42372376e-01]
 [  9.15469050e-01   5.23304415e-02]
 [  5.13534402e-01   8.65152720e-01]
 [  1.76677140e-01   4.48338207e-01]
 [  5.56900794e-01   4.17238242e-02]
 [  3.43416420e-01   2.80675069e-01]
 [  6.61921910e-01   5.18101807e-01]
 [  5.16411467e-01   3.97227287e-01]
 

In [12]:
arr2[:, 1]

array([ 0.39358079,  0.96560639,  0.30095736,  0.83963571,  0.07927995,
        0.39528985,  0.15199891,  0.7840166 ,  0.36121102,  0.70363241,
        0.05233044,  0.44833821,  0.28067507,  0.39722729,  0.36376221,
        0.74177145,  0.51438173,  0.62924221,  0.01492787,  0.35746432,
        0.02401236,  0.37244136,  0.50342552,  0.08001693,  0.68049606])

In [13]:
arr2 * 5

array([[  4.00791849e+00,   1.96790393e+00,   4.91639901e-01,
          3.81898628e+00],
       [  1.12127877e-01,   4.82803194e+00,   1.27506960e-01,
          4.94544293e+00],
       [  4.09530922e+00,   1.50478682e+00,   8.43143319e-01,
          3.78294009e+00],
       [  9.30725076e-01,   4.19817854e+00,   4.01673993e+00,
          4.40679226e+00],
       [  2.71374382e+00,   3.96399745e-01,   1.19922887e+00,
          1.78120436e+00],
       [  4.71783706e+00,   1.97644923e+00,   2.14783633e+00,
          3.25391933e+00],
       [  3.36355743e+00,   7.59994547e-01,   2.74448985e+00,
          2.27157226e+00],
       [  2.83300189e+00,   3.92008299e+00,   4.97073102e+00,
          1.38291783e-01],
       [  3.51134935e+00,   1.80605510e+00,   1.67880518e-05,
          4.96581667e+00],
       [  4.53642684e+00,   3.51816207e+00,   2.93551857e+00,
          4.21186188e+00],
       [  4.57734525e+00,   2.61652208e-01,   2.56767201e+00,
          4.32576360e+00],
       [  8.83385701e

In [14]:
1/ arr2

array([[  1.24753036e+00,   2.54077443e+00,   1.01700452e+01,
          1.30924796e+00],
       [  4.45919438e+01,   1.03561867e+00,   3.92135456e+01,
          1.01103179e+00],
       [  1.22090903e+00,   3.32272980e+00,   5.93018991e+00,
          1.32172329e+00],
       [  5.37215567e+00,   1.19099270e+00,   1.24479057e+00,
          1.13461214e+00],
       [  1.84247311e+00,   1.26135298e+01,   4.16934594e+00,
          2.80708947e+00],
       [  1.05980769e+00,   2.52978925e+00,   2.32792412e+00,
          1.53660847e+00],
       [  1.48652137e+00,   6.57899457e+00,   1.82183221e+00,
          2.20111862e+00],
       [  1.76491234e+00,   1.27548320e+00,   1.00588826e+00,
          3.61554382e+01],
       [  1.42395402e+00,   2.76846482e+00,   2.97830866e+05,
          1.00688373e+00],
       [  1.10218905e+00,   1.42119661e+00,   1.70327657e+00,
          1.18712345e+00],
       [  1.09233622e+00,   1.91093362e+01,   1.94728921e+00,
          1.15586529e+00],
       [  5.66004181e

In [15]:
np.exp(arr2)

array([[ 2.2290683 ,  1.48227903,  1.10332459,  2.14641124],
       [ 1.02267892,  2.62637978,  1.02582933,  2.68878276],
       [ 2.26837075,  1.35115173,  1.18368051,  2.13099289],
       [ 1.20459693,  2.3155233 ,  2.2330045 ,  2.41417702],
       [ 1.72073025,  1.08250733,  1.2710531 ,  1.42795146],
       [ 2.56913024,  1.48481449,  1.53659244,  1.91704295],
       [ 1.9595434 ,  1.16415897,  1.73134397,  1.57509321],
       [ 1.76226582,  2.19025198,  2.70241605,  1.0280444 ],
       [ 2.01832885,  1.43506626,  1.00000336,  2.69976123],
       [ 2.47758766,  2.02108079,  1.79877111,  2.32186879],
       [ 2.49794664,  1.05372388,  1.67118742,  2.37536882],
       [ 1.19324578,  1.56570814,  1.7452552 ,  1.0426065 ],
       [ 1.40975569,  1.32402332,  1.93851441,  1.67883787],
       [ 1.67600245,  1.48769402,  1.00784078,  2.03540809],
       [ 1.97072916,  1.43873205,  2.18928897,  2.07438937],
       [ 1.96828695,  2.09965164,  1.13229339,  1.53961148],
       [ 1.44324151,  1.

In [16]:
np.log(arr2)

array([[ -2.21165887e-01,  -9.32468930e-01,  -2.31944665e+00,
         -2.69452897e-01],
       [ -3.79755321e+00,  -3.49989937e-02,  -3.66902224e+00,
         -1.09713804e-02],
       [ -1.99595687e-01,  -1.20078667e+00,  -1.78005624e+00,
         -2.78936404e-01],
       [ -1.68122926e+00,  -1.74787161e-01,  -2.18967300e-01,
         -1.26290867e-01],
       [ -6.11108748e-01,  -2.53477003e+00,  -1.42775917e+00,
         -1.03214817e+00],
       [ -5.80874681e-02,  -9.28135998e-01,  -8.44976936e-01,
         -4.29577695e-01],
       [ -3.96438740e-01,  -1.88388193e+00,  -5.99842701e-01,
         -7.88965695e-01],
       [ -5.68101024e-01,  -2.43325088e-01,  -5.87099577e-03,
         -3.58782737e+00],
       [ -3.53437520e-01,  -1.01829295e+00,  -1.26042810e+01,
         -6.86014207e-03],
       [ -9.72982493e-02,  -3.51499198e-01,  -5.32553789e-01,
         -1.71533110e-01],
       [ -8.83187224e-02,  -2.95017702e+00,  -6.66438256e-01,
         -1.44849233e-01],
       [ -1.73343128e

In [17]:
arr2[arr2 > 0.5]

array([ 0.8015837 ,  0.76379726,  0.96560639,  0.98908859,  0.81906184,
        0.75658802,  0.83963571,  0.80334799,  0.88135845,  0.54274876,
        0.94356741,  0.65078387,  0.67271149,  0.54889797,  0.56660038,
        0.7840166 ,  0.9941462 ,  0.70226987,  0.99316333,  0.90728537,
        0.70363241,  0.58710371,  0.84237238,  0.91546905,  0.5135344 ,
        0.86515272,  0.55690079,  0.66192191,  0.51810181,  0.51641147,
        0.71069634,  0.67840361,  0.78357682,  0.72966683,  0.6771636 ,
        0.74177145,  0.51438173,  0.62924221,  0.73922846,  0.55696156,
        0.64327976,  0.63429158,  0.93492664,  0.83464559,  0.81603908,
        0.97564126,  0.50342552,  0.98310266,  0.69870588,  0.65032883,
        0.68049606,  0.50580138])

In [18]:
import pandas as pd


In [19]:
from pandas import Series

In [20]:
from pandas import DataFrame

In [28]:
D = {‘left’: [4, 9, 2], ‘center’: [3, 5, 7], ‘right’: [8, 1, 6]}

SyntaxError: invalid syntax (<ipython-input-28-3c0ea49cc2b4>, line 1)

In [29]:
df = DataFrame(D, index = [‘a’, ‘b’, ‘c’])

SyntaxError: invalid syntax (<ipython-input-29-bed56714b285>, line 1)